import Head from 'next/head'

import { Inter } from 'next/font/google'
import Saludo from '@/components/Saludo'

import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
      <Saludo texto="Ale" edad="20">
          <button>Esto es un boton </button>
          <br></br>
          <span> Esto es un Span</span>
        </Saludo>
      </main>
    </>
  )
}
